version: "2"
services:
  frontend:
    stdin_open: true
    tty: true
    container_name: flyby-demo-v1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
